name: client_stripe
description: An idiomatic Dart wrapper for the Stripe REST API.
version: 0.1.3
repository: https://github.com/celest-dev/dart-api-clients/tree/main/clients/stripe

environment:
  sdk: ^3.3.0

dependencies:
  clock: ^1.1.1
  convert: ^3.1.1
  cross_file: ^0.3.4+1
  crypto: ^3.0.3
  http: ">=0.13.0 <2.0.0"
  http_parser: ^4.0.2
  libcoder: ^0.0.1
  logging: ^1.2.0
  meta: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.9
  checks: ^0.3.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.0
