name: Stripe
on:
  pull_request:
    paths:
      - ".github/workflows/stripe.yaml"
      - "clients/stripe/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # 4.2.0
      - name: Setup Dart
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672 # main
        # From: https://docs.stripe.com/stripe-cli#install
      - name: Install Stripe CLI
        run: |
          VERSION=1.21.2
          curl -Lo stripe.tar.gz https://github.com/stripe/stripe-cli/releases/download/v${VERSION}/stripe_${VERSION}_linux_x86_64.tar.gz
          tar xvf stripe.tar.gz
          sudo mv stripe /usr/local/bin/
      # TODO: Update when OpenAPI specs are updated in client
      - name: Install Stripe Mock
        run: |
          VERSION=0.183.0
          URL=https://github.com/stripe/stripe-mock/releases/download/v${VERSION}/stripe-mock_${VERSION}_linux_amd64.deb
          DEB=/tmp/stripe-mock.deb
          curl -Lo $DEB $URL
          sudo dpkg -i $DEB
      - name: Get Packages
        working-directory: clients/stripe
        run: dart pub get
      - name: Test
        working-directory: clients/stripe
        run: dart test --chain-stack-traces --fail-fast --concurrency=1
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_TEST_API_KEY }}
